# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         sapnwrfc
version:      0.17
version_from: sapnwrfc.pm
installdirs:  site
requires:
    Test::More:                    0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
