--- #YAML:1.0
name:                sapnwrfc
version:             0.23
abstract:            sapnwrfc - SAP Netweaver RFC support for Perl
license:             ~
author:              
    - Piers Harding <piers@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
